FROM node:16.15.0-alpine
EXPOSE 3000
RUN mkdir -p /app/public /app/src
WORKDIR /app
COPY .env /app/.env
COPY package.json /app/package.json
COPY package-lock.json /app/package-lock.json
RUN npm install
CMD ["npm", "run", "start"]