version: '3'
services:
    postgres:
        image: postgres:latest
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: 9WS?2bg6ea
        volumes:
            - ./postgresql/data:/var/lib/postgresql/data
    adminer:
        image: adminer
        restart: always
        ports:
        - 8080:8080
    server:
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        ports:
            - "5000:5000"
    client:
        stdin_open: true
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./client:/app
        ports:
            - "3000:3000"
